version: "3"

services:
  api:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:alpine
    container_name: redis_1
    ports:
      - "6379:6379"
